# Generated by Django 6.1.1 on 2026-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='heat0',
            new_name='head0',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='heat1',
            new_name='head1',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='heat2',
            new_name='head2',
        ),
        migrations.AddField(
            model_name='blog',
            name='chead0',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='blog',
            name='chead1',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='blog',
            name='chead2',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
