# Generated by Django 6.1.1 on 2026-09-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_heat0_blog_head0_rename_heat1_blog_head1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
