# Generated by Django 6.1.1 on 2026-09-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ord_id',
            new_name='order_id',
        ),
    ]
